### PR TITLE
feat: add delay prop to support debouncing loadOptions callback

### PR DESCRIPTION
**Pull request by nylon22**

### CODE REVIEW

**Comment by nylon22** [comment]
working on build issues/tests

**Comment by nylon22** [comment]
@TheSharpieOne the tests that are failing on this PR are failing on the master branch as well. Please review this PR when you have a chance.

**Comment by TheSharpieOne** [comment]
I don't think you want to branch from nor PR to master. You probably want to use `v2-async-pagination`.

Also, why not just provide a debounced function to loadOptions?

**Comment by nylon22** [comment]
Thanks - I'll update the target branch of this PR. 

I tried passing in a debounced function to loadOptions. However, there appears to be a timing issue the first time the dropdown is opened. The debounced loadOptions function gets called on page load - but the dropdown stays in a "loading" state even after the loadOptions promise has resolved. As a result, when the dropdown is clicked, it renders the "Loading..." placeholder rather than the results returned from loadOptions function.

**Comment by TheSharpieOne** [comment]
depending on the debounce function and how you are using it, there are a few gotchas with debounce. You mention a promise, if you are using underscore or lodash's debounce or some similar based off of underscore lodash's implementation (such as the one you have included in this PR) you cannot use promises, you have to use callbacks. Those implementations have a "feature" where the debounced function call will immediately return the value from the last time it ran. In the case of returning a promise, it will return the old promise. When you return a value or promise within your loadOptions function, that value or promise is used.
To better illustrate this issue: The user type "t", the debounce function triggered and returned a promise for the result of the "t" network request. The user types "h" (now having "th" in the input), the debounce function will immediately return the promise for "t" since that was the last result.

Also, make sure you cache your debounced function and not create a new one with each render.

I have successfully used debounced everywhere I have used this library. But seeing how I have used it everywhere, it would be a nice feature to have built in.

**Pull request closed without merging**
